# Generated by Django 4.2.1 on 2025-03-01 07:28

from django.db import migrations
import web.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=web.db.models.PriceField(verbose_name='Стоимость'),
        ),
    ]
