# Generated by Django 4.2.1 on 2025-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
