# Generated by Django 4.2.1 on 2025-02-27 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Approved', 'Одобрен'), ('Disapproved', 'Не одобрен'), ('Waiting', 'Ожидает')], default='Waiting', max_length=20, verbose_name='Статус')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('gos_number', models.CharField(max_length=20, verbose_name='Государственный номер')),
                ('vin', models.CharField(max_length=20, verbose_name='ВИН')),
                ('photo', models.ImageField(upload_to='cars/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(db_index=True, max_length=70, null=True, unique=True, verbose_name='Имя пользователя')),
                ('rating', models.FloatField(blank=True, db_index=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tariff', models.CharField(choices=[('Standard', 'Стандартный'), ('Urgent', 'Срочный')], db_index=True, default='Standard', max_length=20, verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
        migrations.CreateModel(
            name='TaxiDriver',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(db_index=True, max_length=70, null=True, unique=True, verbose_name='Имя пользователя')),
                ('rating', models.FloatField(blank=True, db_index=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tariff', models.CharField(choices=[('Standard', 'Стандартный'), ('Urgent', 'Срочный')], db_index=True, default='Standard', max_length=20, verbose_name='Тариф')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Номер телефона')),
                ('passport_data', models.CharField(max_length=30, verbose_name='Паспортные данные')),
                ('passport_photo', models.ImageField(upload_to='passports/', verbose_name='Фото паспорта')),
                ('child_chair', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('is_active', models.BooleanField(default=False, verbose_name='Работает')),
                ('car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='telegram_users.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Таксист',
                'verbose_name_plural': 'Таксисты',
            },
        ),
        migrations.CreateModel(
            name='TariffDriverRequest',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('tariff', models.CharField(choices=[('Standard', 'Стандартный'), ('Urgent', 'Срочный')], db_index=True, default='Standard', max_length=20, verbose_name='Тариф')),
                ('status', models.CharField(choices=[('Approved', 'Одобрен'), ('Disapproved', 'Не одобрен'), ('Waiting', 'Ожидает')], default='Waiting', max_length=20, verbose_name='Статус')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.taxidriver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заявка изменения тарифа',
                'verbose_name_plural': 'Заявки изменения тарифа',
            },
        ),
    ]
