# Generated by Django 4.2.1 on 2025-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxidriver',
            name='reviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
