# Generated by Django 4.2.1 on 2025-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Approved', 'Одобрен'), ('Disapproved', 'Не одобрен'), ('Waiting', 'Ожидает')], default='Waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
