# Generated by Django 4.2.1 on 2025-03-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_taxidriver_reviews_telegramuser_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxidriver',
            name='child_chair',
        ),
    ]
