# Generated by Django 4.2.1 on 2025-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gos_number',
            field=models.CharField(max_length=20, verbose_name='Государственный номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=20, verbose_name='ВИН'),
        ),
    ]
