# Generated by Django 4.2.1 on 2025-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_remove_taxidriver_child_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='points',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
