# Generated by Django 4.2.1 on 2025-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_alter_car_gos_number_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxidriver',
            name='tariff',
            field=models.CharField(choices=[('Standard', 'Стандартный'), ('Urgent', 'Срочный')], db_index=True, default='Standard', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tariff',
            field=models.CharField(choices=[('Standard', 'Стандартный'), ('Urgent', 'Срочный')], db_index=True, default='Standard', max_length=20, verbose_name='Тариф'),
        ),
    ]
