# Generated by Django 4.2.1 on 2025-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_telegramuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='points',
            field=models.PositiveBigIntegerField(default=200, verbose_name='Баллы'),
        ),
    ]
