# Generated by Django 4.2.1 on 2025-03-04 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0005_alter_telegramuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_add_points_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата последнего получения бонусов'),
        ),
    ]
