# Generated by Django 4.2.1 on 2025-03-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0006_telegramuser_last_add_points_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='taxi_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='telegram_users.taxidriver', verbose_name='Таксист'),
            preserve_default=False,
        ),
    ]
