# Generated by Django 4.2.1 on 2025-03-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0007_car_taxi_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='taxi_driver',
            new_name='driver',
        ),
        migrations.AlterField(
            model_name='taxidriver',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_users.car', verbose_name='Авто'),
        ),
    ]
