# Generated by Django 4.2.1 on 2025-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0008_rename_taxi_driver_car_driver_alter_taxidriver_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='front_photo',
            field=models.ImageField(upload_to='cars/fronts/', verbose_name='Фото спереди'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='profile_photo',
            field=models.ImageField(upload_to='cars/profiles/', verbose_name='Фото сбоку'),
            preserve_default=False,
        ),
    ]
