# Generated by Django 4.2.1 on 2025-03-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0009_remove_car_photo_car_front_photo_car_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='reviews',
        ),
    ]
