# Generated by Django 4.2.1 on 2025-02-24 04:51

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tariff', models.CharField(choices=[('ECONOMY', 'Эконом'), ('COMFORT', 'Комфорт'), ('Business', 'Бизнес')], db_index=True, default='ECONOMY', max_length=20, verbose_name='Тариф')),
                ('price', models.PositiveBigIntegerField(verbose_name='Стоимость')),
                ('from_address', models.CharField(max_length=200, verbose_name='Откуда')),
                ('to_address', models.CharField(max_length=200, verbose_name='Куда')),
                ('type', models.CharField(choices=[('Taxi', 'Такси'), ('Delivery', 'Доставка')], default='Taxi', max_length=15, verbose_name='Тип поездки')),
                ('travel_time_minutes', models.PositiveIntegerField(verbose_name='Примерное время поезки')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='telegram_users.taxidriver', verbose_name='Водитель')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='telegram_users.telegramuser', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('price', models.PositiveBigIntegerField(verbose_name='Стоимость')),
                ('type', models.CharField(choices=[('Taxi', 'Такси'), ('Delivery', 'Доставка'), ('Product', 'Товар')], max_length=15, verbose_name='Тип поездки')),
                ('order', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ')),
                ('product', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.product', verbose_name='Товар')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
