# Generated by Django 4.2.1 on 2025-03-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_km', models.PositiveBigIntegerField(verbose_name='Стоимость за километр')),
                ('price_for_travel_minute', models.PositiveBigIntegerField(verbose_name='Стоимость за минуту пути')),
            ],
            options={
                'verbose_name': 'Модель настроек для расчета стоимости заказа',
                'verbose_name_plural': 'Модель настроек для расчета стоимости заказа',
            },
        ),
    ]
