# Generated by Django 4.2.1 on 2025-02-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='from_address_latitude',
            new_name='from_latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='from_address_longitude',
            new_name='from_longitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to_address_latitude',
            new_name='to_latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to_address_longitude',
            new_name='to_longitude',
        ),
    ]
