# Generated by Django 4.2.1 on 2025-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpricesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpricesettings',
            options={'verbose_name': 'Настройки расчета стоимости заказа', 'verbose_name_plural': 'Настройки расчета стоимости заказа'},
        ),
        migrations.AlterField(
            model_name='orderpricesettings',
            name='price_for_km',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Стоимость за километр'),
        ),
        migrations.AlterField(
            model_name='orderpricesettings',
            name='price_for_travel_minute',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Стоимость за минуту пути'),
        ),
    ]
