# Generated by Django 4.2.1 on 2025-03-01 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderpricesettings_default_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='travel_length_km',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator], verbose_name='Длина пути в км'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='travel_time_minutes',
            field=models.PositiveIntegerField(verbose_name='Примерное время поездки в минутах'),
        ),
    ]
