# Generated by Django 4.2.1 on 2025-03-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Taxi', 'Такси'), ('Delivery', 'Доставка'), ('Product', 'Товар')], max_length=15, verbose_name='Тип оплаты'),
        ),
    ]
