# Generated by Django 4.2.1 on 2025-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_current_active_drivers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Не оплачен'), ('Paid', 'Оплачен')], default='Not paid', max_length=8, verbose_name='Статус'),
        ),
    ]
