# Generated by Django 4.2.1 on 2025-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_yookassa_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='yookassa_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_code',
            field=models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='Yookassa payment code'),
            preserve_default=False,
        ),
    ]
