# Generated by Django 4.2.1 on 2025-03-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_payment_yookassa_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='yookassa_payment_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_idempotence_key',
            field=models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='Код платежа yookassa'),
            preserve_default=False,
        ),
    ]
