# Generated by Django 4.2.1 on 2025-03-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_payment_yookassa_payment_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='yookassa_payment_idempotence_key',
            new_name='yookassa_payment_id',
        ),
    ]
