# Generated by Django 4.2.1 on 2025-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_yookassa_payment_idempotence_key_payment_yookassa_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Taxi', 'Такси'), ('Delivery', 'Доставка'), ('Product', 'Продукт')], max_length=15, verbose_name='Тип оплаты'),
        ),
    ]
