# Generated by Django 4.2.1 on 2025-03-09 13:05

from django.db import migrations, models
import web.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_payment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_percent_for_product', web.db.models.PriceField(default=0, verbose_name='Процент боуносов для начисления от цены товара')),
            ],
            options={
                'verbose_name': 'Настройки начисления бонусов',
                'verbose_name_plural': 'Настройки начисления бонусов',
            },
        ),
    ]
