# Generated by Django 4.2.1 on 2025-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_pointssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointssettings',
            name='points_percent_for_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент начисления бонусов от цены товара'),
        ),
    ]
